FIND_PATH(LIBCURL_INCLUDE_DIR NAMES curl.h PATH_SUFFIXES curl)
FIND_LIBRARY(LIBCURL_LIBRARIES NAMES curl)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibCURL DEFAULT_MSG LIBCURL_LIBRARIES
    LIBCURL_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBCURL_INCLUDE_DIR LIBCURL_LIBRARIES)
