FIND_PATH(LIBJSONC_INCLUDE_DIR NAMES json.h PATH_SUFFIXES json)
FIND_LIBRARY(LIBJSONC_LIBRARIES NAMES json)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibJSONC DEFAULT_MSG LIBJSONC_LIBRARIES
    LIBJSONC_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBJSONC_INCLUDE_DIR LIBJSONC_LIBRARIES)
